<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Project;
use Illuminate\Database\Seeder;

class ProjectsTableSeeder extends Seeder
{
    public function run(): void
    {
        $projects = [
            [
                'directorate_id' => 4,
                'title' => 'Tamakoshi-Kathamndu 220/400 kV Transmission Line Project',
                'description' => 'Tamakoshi-Kathamndu 220/400 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Kaligandaki Transmission Corridor Project',
                'description' => 'Kaligandaki Transmission Corridor Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'New Butwal-Bardaghat 220 kV Transmission Line and Substation Project',
                'description' => 'New Butwal-Bardaghat 220 kV Transmission Line and Substation Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Marsyangdi Kathmandu 220 kV Transmission Line Project',
                'description' => 'Marsyangdi Kathmandu 220 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Distribution System Augmentation and Expansion Project',
                'description' => 'Distribution System Augmentation and Expansion Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Grid Substation Reinforcement Project',
                'description' => 'Grid Substation Reinforcement Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Distribution System Master Plan Project',
                'description' => 'Distribution System Master Plan Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Utility Scale Grid Tied Solar Project',
                'description' => 'Utility Scale Grid Tied Solar Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Karnali Solar Energy Project',
                'description' => 'Karnali Solar Energy Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Marsyangdi Corridor 220kV Transmission Line Project',
                'description' => 'Marsyangdi Corridor 220kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Samundratar-Trishuli 132kV Transmission Line Project',
                'description' => 'Samundratar-Trishuli 132kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Lapsiphedi-Changunarayan Substation Construction Project',
                'description' => 'Lapsiphedi-Changunarayan Substation Construction Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Kathmandu Valley Transmission Capacity Reinforcement Project',
                'description' => 'Kathmandu Valley Transmission Capacity Reinforcement Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Kathmandu valley Soth and East Distribution System Enhancement Project ',
                'description' => 'Kathmandu valley Soth and East Distribution System Enhancement Project ',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Kathmandu Valley Smart Metering Project',
                'description' => 'Kathmandu Valley Smart Metering Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Kathmandu Valley Substation Automation Project',
                'description' => 'Kathmandu Valley Substation Automation Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Amlekhgunj Substation Construction Project',
                'description' => 'Amlekhgunj Substation Construction Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Khimti-Barhabise-Lapsiphedi 400kV Substation Construction Project',
                'description' => 'Khimti-Barhabise-Lapsiphedi 400kV Substation Construction Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Kathmandu Valley Transmission Capacity Reinforcement Project-Phase II',
                'description' => 'Kathmandu Valley Transmission Capacity Reinforcement Project-Phase II',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Kathmandu West Distribution System Enhancement Project',
                'description' => 'Kathmandu West Distribution System Enhancement Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Lalitpur-Bhaktapur Distribution System Reinforcement Project',
                'description' => 'Lalitpur-Bhaktapur Distribution System Reinforcement Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Pokhara-Bharatpur Distribution Network Enhancement Project',
                'description' => 'Pokhara-Bharatpur Distribution Network Enhancement Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Province 2 Rural Electrification Project',
                'description' => 'Province 2 Rural Electrification Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Parwanipur-Pokhariya 132kV TL and Pokhariya Substation Project',
                'description' => 'Parwanipur-Pokhariya 132kV TL and Pokhariya Substation Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Electric Vehicle Charging Station Infrastructure Construction Project',
                'description' => 'Electric Vehicle Charging Station Infrastructure Construction Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Distribution Control and Data Center Construction Project',
                'description' => 'Distribution Control and Data Center Construction Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Dandakhet Rahughat 132kV Transmission Line and Substation Project',
                'description' => 'Dandakhet Rahughat 132kV Transmission Line and Substation Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Ghorahi Madichaur 132kV Transmission Line and Substation Project',
                'description' => 'Ghorahi Madichaur 132kV Transmission Line and Substation Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Pangtang Substation Construction Project',
                'description' => 'Pangtang Substation Construction Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Keraun Substation Construction Project',
                'description' => 'Keraun Substation Construction Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => '132kV Transmission Line Upgradation Project',
                'description' => '132kV Transmission Line Upgradation Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Kathmandu Valley Smart Metering Project-Phase II',
                'description' => 'Kathmandu Valley Smart Metering Project-Phase II',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Grid Substation Automation Project-Phase II',
                'description' => 'Grid Substation Automation Project-Phase II',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Dumkibas Substation Construction Project',
                'description' => 'Dumkibas Substation Construction Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Kohalpur-Nepalgunj 132kV Transmission Line and Substation Project',
                'description' => 'Kohalpur-Nepalgunj 132kV Transmission Line and Substation Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Mulpani Substation Construction Project',
                'description' => 'Mulpani Substation Construction Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Chobhar-Lagankhel 132kV Underground Transmission Line and Patan Substation Upgrading Project',
                'description' => 'Chobhar-Lagankhel 132kV Underground Transmission Line and Patan Substation Upgrading Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Institutional Strengthening Project',
                'description' => 'Institutional Strengthening Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Arunpool-Tingla-Newkhimti-Tamakoshi3-Sunkoshi Hub-Dhalkebar 400 kV Transmission Line Project',
                'description' => 'Arunpool-Tingla-Newkhimti-Tamakoshi3-Sunkoshi Hub-Dhalkebar 400 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'New Butwal-Lamahi-Kohalpur-New Attariya 400 kV Transmission Line Project',
                'description' => 'New Butwal-Lamahi-Kohalpur-New Attariya 400 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Okharpauwa Teenpiple 220 kV Transmission Line and Substation Project',
                'description' => 'Okharpauwa Teenpiple 220 kV Transmission Line and Substation Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Dailekh-Kalikot-Jumla 132 kV Transmission Line Project',
                'description' => 'Dailekh-Kalikot-Jumla 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Karnali Electrification Project',
                'description' => 'Karnali Electrification Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'New Butwal-Lamahi 400 kV Transmission Line Project',
                'description' => 'New Butwal-Lamahi 400 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Distributed Solar Project',
                'description' => 'Distributed Solar Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'Disaster Recovery Center Project',
                'description' => 'Disaster Recovery Center Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'New Butwal Kushma Substation Expansion Project',
                'description' => 'New Butwal Kushma Substation Expansion Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 4,
                'title' => 'NEA Digitization and SCADA Expansion Project',
                'description' => 'NEA Digitization and SCADA Expansion Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],

            [
                'directorate_id' => 2,
                'title' => 'Singati-Lamosanghu 132 kV Transmission Line Project',
                'description' => 'Singati-Lamosanghu 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Ramechhap-Garjyang-Khimti 132 kV Transmission Line Project',
                'description' => 'Ramechhap-Garjyang-Khimti 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Kushma- Lower Modi 132 kV Transmission Line Project',
                'description' => 'Kushma- Lower Modi 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Kushaha- Kataiya (Second Circuit) 132 kV Transmission Line Project',
                'description' => 'Kushaha- Kataiya (Second Circuit) 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Raxual- Parwanipur (Second Circuit) 132 kV Transmission Line Project',
                'description' => 'Raxual- Parwanipur (Second Circuit) 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'New Modi- Lekhnath 132 kV Transmission Line Project',
                'description' => 'New Modi- Lekhnath 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Solu Corridor 132 kV Transmission Line Project',
                'description' => 'Solu Corridor 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Burtibang-Paudi-Amrai-Tamghas-Sandhikharka-Gorusinghe 132 kV Transmission Line Project',
                'description' => 'Burtibang-Paudi-Amrai-Tamghas-Sandhikharka-Gorusinghe 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Kushaha- Biratnagar 132 kV Transmission Line Project',
                'description' => 'Kushaha- Biratnagar 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Balefi- Barhabishe 132 kV Transmission Line Project',
                'description' => 'Balefi- Barhabishe 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Dordi Corridor 132 kV Transmission Line Project',
                'description' => 'Dordi Corridor 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Purbi Chitwan 132 kV Transmission Line Project',
                'description' => 'Purbi Chitwan 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Dhalkebar- Loharpatti 132 kV Transmission Line Project',
                'description' => 'Dhalkebar- Loharpatti 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Amarpur- Dhungesanghu 132 kV Transmission Line Project',
                'description' => 'Amarpur- Dhungesanghu 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Kohalpur- Surkhet- Dailekh 132 kV Transmission Line Project',
                'description' => 'Kohalpur- Surkhet- Dailekh 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Dhalkebar- Balganga 132 kV Transmission Line Project',
                'description' => 'Dhalkebar- Balganga 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Lalbandhi- Nawalpur- Salempur 132 kV Transmission Line Project',
                'description' => 'Lalbandhi- Nawalpur- Salempur 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Bhumahi- Hakui 132 kV Transmission Line Project',
                'description' => 'Bhumahi- Hakui 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Godak- Anarmani 132 kV Transmission Line Project',
                'description' => 'Godak- Anarmani 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Bafikot- Khungri 132 kV Transmission Line Project',
                'description' => 'Bafikot- Khungri 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Sunkoshi  132 kV Substation Project',
                'description' => 'Sunkoshi  132 kV Substation Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Sampatiya- Mainhiya 132 kV Transmission Line Project',
                'description' => 'Sampatiya- Mainhiya 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Godak- Soyak 132 kV Transmission Line Project',
                'description' => 'Godak- Soyak 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Rupani- Bodebarsain 132 kV Transmission Line Project',
                'description' => 'Rupani- Bodebarsain 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Chandrapur- Sukdevchok 132 kV Transmission Line Project',
                'description' => 'Chandrapur- Sukdevchok 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Lahan- Sukhipur 132 kV Transmission Line Project',
                'description' => 'Lahan- Sukhipur 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Bhaktapur-Baneswor-Patan  66 kV Transmission Line Upgradation Project',
                'description' => 'Bhaktapur-Baneswor-Patan  66 kV Transmission Line Upgradation Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Surkhet 132 kV Substation Project',
                'description' => 'Surkhet 132 kV Substation Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Pokhara- Birauta 132 kV Transmission Line Project',
                'description' => 'Pokhara- Birauta 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Syaule- Sanfebagar 132 kV Transmission Line Project',
                'description' => 'Syaule- Sanfebagar 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Kathmandu Valley System Upgradation Project',
                'description' => 'Kathmandu Valley System Upgradation Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Malekhu 132 kV Substation Expansion Project',
                'description' => 'Malekhu 132 kV Substation Expansion Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Newkhimti-Lamosanghu Kathmandu Transmission Line Upgradation Project',
                'description' => 'Newkhimti-Lamosanghu Kathmandu Transmission Line Upgradation Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Prasauni- Birgunj 132 kV Underground Transmission Line Project',
                'description' => 'Prasauni- Birgunj 132 kV Underground Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Butwal- Lumbini 132 kV Transmission Line Project',
                'description' => 'Butwal- Lumbini 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Attariya- Dhangadi 132 kV Transmission Line Project',
                'description' => 'Attariya- Dhangadi 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Damak-Keraun-Biratnagar  132 kV Transmission Line Project',
                'description' => 'Damak-Keraun-Biratnagar  132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Dhaubadi-Meghauli 132 kV Transmission Line Project',
                'description' => 'Dhaubadi-Meghauli 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Auraha-Simara 132 kV Transmission Line Project',
                'description' => 'Auraha-Simara 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => '132 kV Transmission Line Upgradation Project',
                'description' => '132 kV Transmission Line Upgradation Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Singati 132 kV Substation Project',
                'description' => 'Singati 132 kV Substation Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Nepalgunj-Nanpara 132 kV Transmission Line Project',
                'description' => 'Nepalgunj-Nanpara 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Transmission Line Study Project',
                'description' => 'Transmission Line Study Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Hetauda-Bharatpur 220 kV Transmission Line Project',
                'description' => 'Hetauda-Bharatpur 220 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Bharatpur-Bardaghat 220 kV Transmission Line Project',
                'description' => 'Bharatpur-Bardaghat 220 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Koshi Corridor 220 kV Transmission Line Project',
                'description' => 'Koshi Corridor 220 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Trishuli 3B Hub Substation Project',
                'description' => 'Trishuli 3B Hub Substation Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Chilime-Trishuli 220 kV Transmission Line Project',
                'description' => 'Chilime-Trishuli 220 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Lekhnath-Damauli 220 kV Transmission Line Project',
                'description' => 'Lekhnath-Damauli 220 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Dharan 220/33 kV Substation Project',
                'description' => 'Dharan 220/33 kV Substation Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Tumlingtar-Sitalpati 220 kV Transmission Line Project',
                'description' => 'Tumlingtar-Sitalpati 220 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Trishuli 3B-Ratmate-Galchhi 220 kV Transmission Line Project',
                'description' => 'Trishuli 3B-Ratmate-Galchhi 220 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Palpa 220/132 kV Substation Project',
                'description' => 'Palpa 220/132 kV Substation Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Gandak-Nepalgunj  220 kV Transmission Line Project',
                'description' => 'Gandak-Nepalgunj  220 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'South Corridor Transmission System Consultancy Service Project',
                'description' => 'South Corridor Transmission System Consultancy Service Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Kathmandu Valley Transmission System Expansion Project (Co-ordinator)',
                'description' => 'Kathmandu Valley Transmission System Expansion Project (Co-ordinator)',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Kathmandu Valley Transmission System Expansion Project (Package A)',
                'description' => 'Kathmandu Valley Transmission System Expansion Project (Package A)',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Kathmandu Valley Transmission System Expansion Project (Package B)',
                'description' => 'Kathmandu Valley Transmission System Expansion Project (Package B)',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Kathmandu Valley Transmission System Expansion Project (Package C)',
                'description' => 'Kathmandu Valley Transmission System Expansion Project (Package C)',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Kathmandu Valley Transmission System Expansion Project (Package D)',
                'description' => 'Kathmandu Valley Transmission System Expansion Project (Package D)',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Kathmandu Valley Transmission System Expansion Project (Package E)',
                'description' => 'Kathmandu Valley Transmission System Expansion Project (Package E)',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],

            [
                'directorate_id' => 2,
                'title' => 'Nijgad 400 kV Substation  Project',
                'description' => 'Nijgad 400 kV Substation  Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Nijgad-Harnaiya 400 kV Transmission Line Project',
                'description' => 'Nijgad-Harnaiya 400 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Harnaiya-Inaruwa 400 kV Transmission Line Project',
                'description' => 'Harnaiya-Inaruwa 400 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Hetauda Dhalkebar Inaruwa 400 kV Substation Expansion Project',
                'description' => 'Hetauda Dhalkebar Inaruwa 400 kV Substation Expansion Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Arun-Inaruwa-Tingla-Mirchaiya 400 kV Transmission Line Project',
                'description' => 'Arun-Inaruwa-Tingla-Mirchaiya 400 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Inaruwa-Anarmani 400 kV Transmission Line Project',
                'description' => 'Inaruwa-Anarmani 400 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Ratmate-Rasuwagadhi-Kerung 400 kV Transmission Line Project',
                'description' => 'Ratmate-Rasuwagadhi-Kerung 400 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Hetauda-Dhalkebar-Inaruwa 400 kV Transmission Line Project',
                'description' => 'Hetauda-Dhalkebar-Inaruwa 400 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 2,
                'title' => 'Thankot-Chapagaun-Bhaktapur 132 kV Transmission Line Project',
                'description' => 'Thankot-Chapagaun-Bhaktapur 132 kV Transmission Line Project',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,

                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 1,
                'title' => 'मातातीर्थ मार्खु ३३ के.भी. सबस्टेशन आयोजना',
                'description' => 'मातातीर्थ मार्खु ३३ के.भी. सबस्टेशन आयोजना',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,
                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 1,
                'title' => 'रसुवा नुवाकोट ३३ के.भी. सवस्टेशन आयोजना',
                'description' => 'रसुवा नुवाकोट ३३ के.भी. सवस्टेशन आयोजना',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,
                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 1,
                'title' => 'सौर्य उर्जा प्रवर्दन आयोजना (नयाँ)',
                'description' => 'सौर्य उर्जा प्रवर्दन आयोजना (नयाँ)',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,
                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 1,
                'title' => 'पावर डिष्ट्रीवुसन स्ट्रेङ्थिङ प्रोग्राम (PoDiSP) (नयाँ)',
                'description' => 'पावर डिष्ट्रीवुसन स्ट्रेङ्थिङ प्रोग्राम (PoDiSP) (नयाँ)',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,
                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 1,
                'title' => 'मदनकुडारी मकैवारी सिंगटी ३३ के.भी. प्रशारण लाइन तथा सवस्टेशन आयोजना',
                'description' => 'मदनकुडारी मकैवारी सिंगटी ३३ के.भी. प्रशारण लाइन तथा सवस्टेशन आयोजना',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,
                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 1,
                'title' => 'खोकना निजगढ ३३/११ के.भी. सवस्टेशन आयोजना',
                'description' => 'खोकना निजगढ ३३/११ के.भी. सवस्टेशन आयोजना',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,
                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 1,
                'title' => 'सामूदायिक विद्यालय एवं सामूदायिक खानेपानिको लागी विद्युत विस्तार आयोजना',
                'description' => 'सामूदायिक विद्यालय एवं सामूदायिक खानेपानिको लागी विद्युत विस्तार आयोजना',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,
                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 1,
                'title' => 'दार्चुला र डोल्पा ग्रामिण बिधुतिकरण आयोजना (नया)',
                'description' => 'दार्चुला र डोल्पा ग्रामिण बिधुतिकरण आयोजना (नया)',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,
                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 1,
                'title' => 'भोजपुर , संखुवासभा ११/०.४ के. भी. ग्रामिण बिधुतिकरण आयोजना',
                'description' => 'भोजपुर , संखुवासभा ११/०.४ के. भी. ग्रामिण बिधुतिकरण आयोजना',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,
                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 1,
                'title' => 'नवलपुर ग्रामिण बिधुतिकरण तथा छुसांग (मुस्तांग ) ३३ के. भी. प्रसारण लाइन तथा सबस्टेसन निर्माण आयोजना',
                'description' => 'नवलपुर ग्रामिण बिधुतिकरण तथा छुसांग (मुस्तांग ) ३३ के. भी. प्रसारण लाइन तथा सबस्टेसन निर्माण आयोजना',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,
                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 1,
                'title' => 'Distribution System Reliability and Substation सुधार आयोजना',
                'description' => 'Distribution System Reliability and Substation सुधार आयोजना',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,
                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 1,
                'title' => 'वितरण प्रणाली सुदृढीकरण तथा चुहावट नियन्त्रण आयोजना',
                'description' => 'वितरण प्रणाली सुदृढीकरण तथा चुहावट नियन्त्रण आयोजना',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,
                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 1,
                'title' => 'वितरण प्रणाली भोल्टेज सुधार (capacitor Bank) आयोजना',
                'description' => 'वितरण प्रणाली भोल्टेज सुधार (capacitor Bank) आयोजना',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,
                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 1,
                'title' => 'वितरण सबस्टेसन अटोमेशन आयोजना (नया)',
                'description' => 'वितरण सबस्टेसन अटोमेशन आयोजना (नया)',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,
                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 1,
                'title' => 'Electricity Supply Reliability Improvement Project (ESRP)',
                'description' => 'Electricity Supply Reliability Improvement Project (ESRP)',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,
                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 1,
                'title' => 'नेपाल वितरण प्रणली स्तरोन्नती तथा विस्तार आयोजना (EIB)',
                'description' => 'नेपाल वितरण प्रणली स्तरोन्नती तथा विस्तार आयोजना (EIB)',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,
                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
            [
                'directorate_id' => 1,
                'title' => 'नेपाल वितरण प्रणली स्तरोन्नती तथा विस्तार आयोजना (AIIB) ',
                'description' => 'नेपाल वितरण प्रणली स्तरोन्नती तथा विस्तार आयोजना (AIIB) ',
                'start_date' => '2017-01-24 18:00:13',
                'end_date' => null,
                'status_id' => 2,
                'priority_id' => 3,
                'progress' => 15,
                'project_manager' => 1,
                'created_at' => '2022-01-24 18:00:13',
                'updated_at' => '2022-01-24 18:00:13',
                'deleted_at' => null,
            ],
        ];

        Project::insert($projects);
    }
}
